const STATUS_OK = 200;
const STATUS_BAD_REQUEST = 400;
const STATUS_UNAUTHORIZED = 401;
module.exports = {
    STATUS_BAD_REQUEST: STATUS_BAD_REQUEST,
    STATUS_UNAUTHORIZED: STATUS_UNAUTHORIZED,
    STATUS_OK: STATUS_OK
};
